#!/bin/bash

babel kcmap.es > kcmap.js

[[ -n "$@" ]] && fl="$@" || fl=$(ls source)

for w in $fl; do
    if [[ -d "source/$w" ]]; then
        echo ">>> $w"
        cp source/$w/* .
        node kcmap.js
        [[ -f spots_unamed.json ]] && mv spots_unamed.json "source/$w/"
        [[ -f draw.svg ]] && mv draw.svg "built/$w.svg"
        [[ -f poi.json ]] && mv poi.json "poi/$w.json"
    fi
done

node kcmap.js clean
